# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 90
# Issues with these labels will never be considered stale
exemptLabels:
  - good first issue
  - help wanted
  - security
  - user-story
  - Never stale
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  🚨This issue has been automatically marked as stale because it has not had recent activity.🚨 
  
  If you are still interested in this issue, please, leave a comment stating its current status. 
  Note that if no development resources has been allocated on it, you may need to search for 
  alternative resources to complete it. **It will be closed if no further activity occurs.**
  
  Thank you for your contributions.
# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This has been closed due to inactivity. If you want to further pursue this
  development, please reopen it again adding the new information.
